// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZmD7_hSxvmOUAolk6uzRyTa3wWVQxPSc',
    appId: '1:491061260039:web:d811aec4b4e2c76fb1dfa2',
    messagingSenderId: '491061260039',
    projectId: 'authtutorial-fe146',
    authDomain: 'authtutorial-fe146.firebaseapp.com',
    databaseURL: 'https://authtutorial-fe146-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authtutorial-fe146.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUasLv_kqDqiN9gsNVFWH3VFZrEqZpUsQ',
    appId: '1:491061260039:android:9f8b5fc81bd8831eb1dfa2',
    messagingSenderId: '491061260039',
    projectId: 'authtutorial-fe146',
    databaseURL: 'https://authtutorial-fe146-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authtutorial-fe146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApalPEOJB_IKZzO73uoj0WfN5Q_wsnXow',
    appId: '1:491061260039:ios:349d2ac1c63b6529b1dfa2',
    messagingSenderId: '491061260039',
    projectId: 'authtutorial-fe146',
    databaseURL: 'https://authtutorial-fe146-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authtutorial-fe146.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApalPEOJB_IKZzO73uoj0WfN5Q_wsnXow',
    appId: '1:491061260039:ios:06cfdadfcedfb0b9b1dfa2',
    messagingSenderId: '491061260039',
    projectId: 'authtutorial-fe146',
    databaseURL: 'https://authtutorial-fe146-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'authtutorial-fe146.appspot.com',
    iosBundleId: 'com.example.loginapp.RunnerTests',
  );
}
